#!/bin/bash

[ $1 ] || {
	echo "Missing workdir";
	exit 1
}

workdir=$(readlink -m $1)

for p in $(ls $workdir/snaps); do
	btrfs subvolume delete $workdir/snaps/$p
done
btrfs subvolume delete $workdir/workdir
rm -rf $workdir