#!/bin/bash

[ $1 ] || {
	echo "Missing workdir"
	exit 1
}

workdir=$(readlink -m $1)
scriptlocation=$(dirname "${BASH_SOURCE[0]}")
dev=$($scriptlocation/_whichdev $workdir)
mountPoint=/tmp/$RANDOM

mkdir -p $mountPoint

mount -t btrfs -o subvolid=0 $dev $mountPoint

if [ "$?" == "0" ]; then
	for p in $(ls $mountPoint/.snaps$workdir/snaps | head -n -1); do
		echo $p : $(date --date="@$p")
	done

	umount $mountPoint
else
	echo "Unable to mount $dev on $mountPoint"
fi

rmdir $mountPoint