#!/bin/bash

[ $1 ] || {
	echo "Missing workdir"
	exit 1
}

[ $2 ] || {
	echo "Missing id"
}

workdir=$(readlink -m $1)
scriptlocation=$(dirname "${BASH_SOURCE[0]}")
snapid=$2

if [ -d $workdir/snaps/$snapid ]; then
		
	# Snap current
	$scriptlocation/_snap $workdir

	btrfs sub del $workdir/workdir

	if [ "$?" == "0" ]; then
		btrfs sub snapshot $workdir/snaps/$snapid $workdir/workdir
	else 
		echo "Unable to remove main volume"
	fi
else
	echo "Snap $snapid not found!"
fi
