#!/bin/bash

set -x

while [ "$#" -gt "0" ]; do
	arg=$1
	shift
	case $arg in
		"-m")
			message=$1
			shift
			;;
		*)
			if [ "$workdir" == "" ]; then
				workdir=$arg
			else
				echo "Too many arguments"
				exit 1
			fi
	esac
done

[ $workdir ] || {
	echo "Missing workdir"
	exit 1
}

workdir=$(readlink -m $workdir)
snapshot=$(date +%s)

if [ "$message" != "" ]; then
        echo "$message" > $workdir/workdir/.snapmessage
fi

btrfs sub snapshot -r $workdir/workdir $workdir/snaps/$snapshot
sync

rm $workdir/workdir/.snapmessage
