#!/bin/bash

[ $1 ] || {
	echo "Missing workdir"
	exit 1
}

[ $2 ] || {
	echo "Missing remote host"
	exit 2
}

[ $3 ] || {
	echo "Missing remote dir"
	exit 3
}

host=$2
dest=$3
snapsdir=$(readlink -m $1)/snaps

echo "Creating dest directory if not exists..."
ssh $host mkdir -p $dest

echo "Listing remote shapshots..."
remoteSnapshots=$(ssh $host ls $dest)

echo "Listing local snapshots..."
localSnapshots=$(ls $snapsdir)

echo "Cleaning remote snapshots..."
for remoteSnapshot in $remoteSnapshots; do
	if [ ! -e $snapsdir/$remoteSnapshot ]; then
		ssh $host sudo btrfs subvolume delete $dest/$remoteSnapshot
	fi
done

# Check have at least the first snapshot
echo "Bootstraping first snapshot..."
firstSnapshot=$(ls $snapsdir | head -1)
ssh $host test -e $dest/$firstSnapshot
if [ ! $? ]; then
	sudo btrfs send $snapsdir/$firstSnapshot | ssh $host sudo btrfs receive $dest
fi

echo "Processing incremental backup..."
previous=$firstSnapshot
for p in $(ls $snapsdir | tail -n +2); do
	ssh $host test -e $dest/$p || \
		sudo btrfs send -p $snapsdir/$previous $snapsdir/$p | ssh $host sudo btrfs receive $dest
	previous=$p
done


