#!/bin/bash

set -x

[ $1 ] || {
	echo "Missing workdir"
	exit 1
}

[ $2 ] || {
	echo "Missing remote"
}

[ $3 ] || {
	echo "Missing remote dir"
}

workdir=$(readlink -m $1)
scriptlocation=$(dirname "${BASH_SOURCE[0]}")
remote=$2
remotedir=$3
rosnapsdir=$workdir/ro

mkdir -p $rosnapsdir

for p in $(ls $workdir/snaps); do
	btrfs sub snapshot -r $workdir/snaps/$p $rosnapsdir/$p
done
sync

firstSnapshot=$(ls $rosnapsdir | head -1)

ssh $remote mkdir -p $remotedir
ssh $remote test -e $remotedir/$firstSnapshot
if [ "$?" != 0 ]; then # First snapshot not found
	btrfs send $rosnapsdir/$firstSnapshot |ssh $remote sudo btrfs receive $remotedir
fi

previous=$firstSnapshot
for p in $(ls $rosnapsdir | tail -n +2); do
	btrfs send -p $rosnapsdir/$previous $rosnapsdir/$p |ssh $remote sudo btrfs receive $remotedir
done

for p in $(ls $rosnapsdir); do
	btrfs sub del $rosnapsdir/$p
done
sync

rmdir $rosnapsdir